### ISSUE TITLE
Проверить  InitialsService

### ISSUE THREAD

**Issue by taxa222** [taxa222/InitialsServiceCalculate#2]

**Comment by taxa222** [comment]
check=>>https://github.com/taxa222/InitialsServiceCalculate/commit/108e3087c7a5a02b35aa66d077734b6dc22015b3

**Comment by taxa222** [comment]
уточнение в 58267b9ce2029b394a4975c5763b271b65b5628a

**Comment by coursar** [comment]
Пофиксить #4
