### ISSUE TITLE
Что проверяет этот тест?

### ISSUE THREAD

**Issue by coursar** [taxa222/InitialsServiceCalculate#6]
https://github.com/taxa222/InitialsServiceCalculate/blob/c03e771d88e17234641adb972134426b21863499/src/test/java/ru/itpark/InitialsServiceCalculateTest.java#L13-L20

**Comment by taxa222** [comment]
@coursar  тест на проверку ,что 2 объекта не равны ,   задача с выводом инициалом работает

**Comment by coursar** [comment]
Я вижу только то, что вы сравниваете `input` с `null`, а `expected` с 0.

По факту же вы должны сравнивать, что вычисление инициалов работает корректно: подаёте строку 'Ivan Petrov' получаете 'IP'

**Comment by taxa222** [comment]
@coursar  9d28aa8300bd74ca0db45e64be2a3295cec6c3cc исправил, но не работает Huan Pedro Rodriges---HR  and ivan petrov--IP

**Comment by coursar** [comment]
Поставьте точку остановки здесь:

https://github.com/taxa222/InitialsServiceCalculate/blob/c03e771d88e17234641adb972134426b21863499/src/main/java/ru/itpark/InitialsServiceCalculate.java#L12-L13

И посмотрите, почему не работает.
